=== Francis1104Ol/Uopeople_webdevtask/week7/catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Root element -->
    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>

                        <xs:sequence>
                            <xs:element name="title">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="publicationYear" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="author">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstName" type="xs:string"/>
                                        <xs:element name="lastName" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="available" type="xs:boolean" use="required"/>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Francis1104Ol/Uopeople_webdevtask/week7/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>

<catalog 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="catalog.xsd">

    <book id="B1" available="true">
        <title>
            <name>The Great Gatsby</name>
            <publicationYear>1925</publicationYear>
        </title>

        <author>
            <firstName>F. Scott</firstName>
            <lastName>Fitzgerald</lastName>
        </author>
    </book>

</catalog>
